reference: "idbastar_v0"

default:
  max_num_sol: 1
quad2d_v0:
  default:
    motionsFile: ../dynomotions/quad2d_v0_all_im.bin.sp.bin.ca.bin.small5000.msgpack
quad3d_v0:
    motionsFile: ../dynomotions/quad3d_v0_all3.bin.im.bin.sp1.bin.ca.bin.small5000.msgpack

